Fix missing "-jar" option
Without it will get an error message like:

Error: Could not find or load main class target.scala-2.10.order-book-dynamics1.jar